### ISSUE TITLE
Enemies spawned from file flicker

### ISSUE THREAD

**Issue by Craigspaz** [Craigspaz/OverDogg-Studios-Keystone-Java#70]

**Comment by kfalicov** [comment]
Found issue, working on solution (move method in Enemy was overwritten)

**Comment by Craigspaz** [comment]
Issue had to do with the animation was using the wrong texture coordinates. That enemy will not be used in the final game. @kfalicov We need to make sure that new enemies have properly mapped texture coordinates.
